export const en = {
  initialView: {
    login1: 'Continue with Apple',
    login2: 'Continue with Google',
    login3: 'Continue with Facebook',
    seed: 'Login with existing Terra wallet',
  },
  agreeView: {
    button: 'Trade at your own risk',
  },
  pinSecurityView: {
    notMatch: 'Passwords do not match. Please try again',
    changed: 'Password has been successfully changed',
    lockedTitle: 'Authentication disabled',
    lockedMessage: 'Please try again in 1 minute',
    authTitle: 'Type in password',
    newTitle: 'Set your password',
    newSubTitle: 'Enter a new 6-digit password to\nunlock your Mirror Wallet',
    newReTitle: 'Confirm your password',
    newReSubTitle:
      'You will only be able to reset your password\nwith your connected account',

    forgotMessage:
      'Please log out of the Mirror Wallet application and re-sign in using your connected Apple/Google/Facebook account to reset your 6-digit password.',
    forgotButton1: 'Cancel',
    forgotButton2: 'Logout',
    forgotPassword: 'Forgot Password',
  },
  bioAuthView: {
    useTouchId: 'Use Touch ID',
    useTouchIdSub: 'Use Touch ID for faster and\neasier access to your account',
    useFaceId: 'Use Face ID',
    useFaceIdSub: 'Use Face ID for faster and\neasier access to your account',
    biometricFailMsg:
      'Biometric authentication failed. Did you rejected permission request?',
    authReason: 'Enable Touch ID for Mirror',
    authTitle: 'Confirm your fingerprint',
    bioErrorTitle: 'Biometric error',
    bioErrorMsg: 'Biometric authentication failed.',
    later: 'Later',
    enable: 'ENABLE',
  },
  mainView: {
    portfolio: 'Portfolio',
    invest: 'Invest',
    searchPlaceholder: 'Discover a Mirror Asset',
  },
  mainTab1View: {
    buyingPower: 'Buying Power',
    balance: 'Balance',
    invested: 'Invested',
    uninvested: 'Un-Invested',
    investedbalance: 'Invested Balance',

    polishYourPortfolio: 'Invest with\nMirror',
    depositToMirror: 'Deposit to\nMirror',
    startInvestingNowWith: 'Start investing now with',
    availableToInvest: 'available to invest',
    deposit: 'Deposit Now',
    symbol: 'UST',
  },
  mainTab2View: {
    mirrorAsset: 'Mirror Asset',
    sortby: 'Sort by',
    done: 'Done',
    ticker: 'Ticker',
    price: 'Price',
    change: '% Change',
  },
  investedDetailView: {
    investedDetail: 'Invested Detail',
    currentValue: 'Current Value',
    amount: 'Amount',
    avgCost: 'Avg Cost',
    ret: 'Return',
    pl: 'UnRealized P/L',
    about: 'About',
    showmore: 'Show More',
    showless: 'Show Less',
    news: 'News',
    buy: 'Buy',
    sell: 'Sell',
  },
  tradeStep1View: {
    availableTo: 'available to',
    buy: 'buy',
    availableToSell: 'available to sell',
    next: 'Next',
  },
  tradeStep2View: {
    amount: 'AMOUNT',
    fees: 'FEES',
    buyingPrice: 'BUYING PRICE',
    inclSpread: 'incl. Spread',
    sellingPrice: 'SELLING PRICE',
    editBuyOrder: 'Reset buy order',
    editSellOrder: 'Reset sell order',
    spread: 'Spread',

    notice: 'NOTICE',
    noticedesc:
      'Mirror Assets do not afford any rights of the underlying asset to Mirror Asset holders. Tracking error may also arise between the underlying asset and its Mirror counterpart.',
    confirm: 'Confirm',

    exceed: 'Fees exceed total trade value.',
  },
  searchView: {
    discover: 'Discover a Mirror Asset',
    cancel: 'Cancel',
  },
  processingView: {
    buySuccess: 'Buy order success',
    sellSuccess: 'Sell order success',
    withdrawSuccess: 'Withdraw success',
    swapSuccess: 'Swap success',
    done: 'Done',
  },
  addressPopupView: {
    address: 'Address',
    qrcode: 'QR code',
    done: 'Done',
    copy: 'Copy',
    copied: 'Copied',
  },
  walletSummaryView: {
    wallet: 'Wallet',
    depositUST: 'Deposit UST',
    funds: 'Funds',
    fundYourWallet: 'Fund Your Wallet',
    deposit: 'Deposit',
    withdrawal: 'Withdrawal',
    depositNow: 'Deposit Now',
    buyNow: 'Buy Now',
    masset: 'mASSET',
    addMasset: '+ mASSET',
    showDecimals: 'Show Decimals',
    depositUpper: 'DEPOSIT',
    withdrawUpper: 'WITHDRAW',
  },
  walletDetailView: {
    notice: 'NOTICE',
    noticedesc:
      'Terra stablecoins other than UST (USD-pegged) must be swapped into UST before Mirror Assets can be purchased.',
    withdraw: 'Withdraw',
    deposit: 'Deposit',
    depositUpper: 'DEPOSIT',
    withdrawUpper: 'WITHDRAW',
  },
  swapView: {
    availableToSwap: 'available to swap',
    swapTo: 'Swap to',
    fees: 'Fees',
  },
  walletTopupView: {
    deposit: 'Deposit',
    pending: 'Pending',
  },
  withdrawView: {
    withdraw: 'Withdraw',
    availableToWithdraw: 'available to withdraw',
    quantity: 'QUANTITY',
    amount: 'AMOUNT',
    address: 'ADDRESS',
    memo: 'MEMO',
    next: 'Next',
  },
  withdrawDetailView: {
    amount: 'AMOUNT',
    fees: 'FEES',
    quantity: 'QUANTITY',
    address: 'ADDRESS',
    memo: 'MEMO',
    withdraw: 'Withdraw',
    insufficientFunds: 'Insufficient Funds',
    notice: 'NOTICE',
    noticedesc:
      'When withdrawing your funds or assets, associated transaction fees are algorithmically decided and charged by the Terra Protocol.',
  },
  privacyView: {
    privacyAndTerms: 'Privacy and terms',
  },
  versionView: {
    version: 'Version',
    current: 'Current',
    newest: 'Newest',
    update: 'Update',
  },
  walletInfoView: {
    walletAddress: 'Wallet address',
    appleAccount: 'Apple ID',
    facebookAccount: 'Facebook Account',
    googleAccount: 'Google Account',
    linkedAccount: 'Linked Account',
    copy: 'Copy',
    copied: 'Copied',
    logout: 'Log out',
  },
  settingView: {
    setting: 'Setting',
    account: 'Account',
    useTouchId: 'Use Touch ID',
    useFaceId: 'Use Face ID',
    biometricAuthHintIOS:
      'It seems Face ID permission is denied or biometric authentication is not enrolled.',
    biometricAuthHintAndroid: 'Biometric authentication is not enrolled.',
    changePassword: 'Change Password',
    privacyAndTerms: 'Privacy and Terms',
    version: 'Version',
    contactUs: 'Contact Us',
    language: 'language',
    selectChain: 'Select Chain',
    selectTorusNet: 'Select TorusNet',
    resetApp: 'Apply and reset',
  },
  walletActivityView: {
    activity: 'Activity',
    all: 'All',
    buy: 'Buy',
    sell: 'Sell',
    deposit: 'Deposit',
    swap: 'Swap',
    withdraw: 'Withdraw',
    empty: 'No past transaction activity',
    itemView: {
      buy: 'Buy',
      sell: 'Sell',
      swap: 'Swap',
      swapTo: 'Swap to',
      deposit: 'Deposit',
      withdraw: 'Withdraw',
      registration: 'REGISTRATION',
    },
  },
  walletActivityFilterView: {
    sortBy: 'Sort by',
    done: 'Done',
    all: 'All',
    buy: 'Buy',
    sell: 'Sell',
    deposit: 'Deposit',
    swap: 'Swap',
    withdraw: 'Withdraw',
    confirm: 'Confirm',
  },
  walletActivityDetailView: {
    orderAmount: 'Order amount',
    senderAddress: 'Sender Address',
    withdrawAddress: 'Withdraw Address',
    amount: 'Amount',
    from: 'From',
    to: 'To',
    quantity: 'Quantity',
    excutionPrice: 'Execution Price',
    fees: 'Fees',
    memo: 'Memo',
    txHash: 'TX Hash',
    buy: 'Buy',
    sell: 'Sell',
    deposit: 'Deposit',
    swap: 'Swap',
    swapTo: 'Swap to',
    withdraw: 'Withdraw',
    registration: 'REGISTRATION',
  },
  spreadPopupView: {
    title: 'Spread',
    content:
      'The estimated spread for the above transaction is algorithmically decided by the Mirror Protocol.',
    more: 'Learn More',
    close: 'Done',
  },
  moonpayPopupView: {
    completedTitle: 'MoonPay Deposit Completed',
    failedTitle: 'MoonPay Deposit Failed',
    completedMessageWithdraw: ' has been successfully withdrawn as ',
    completedMessage1:
      ' has been successfully deposited into your Mirror Wallet.',
    failedMessage1: 'Your MoonPay transaction for ',
    failedMessage2:
      ' has failed. For more detailed information, please check your transaction details on the MoonPay webpage.',
    details: 'Details',
    symbol: 'UST',
    done: 'Done',
  },
  onboardingView: {
    title1: 'What are Mirror Assets?',
    content1_1:
      'Mirror Assets utilize blockchain technology to track the price of underlying assets in real markets but do ',
    content1_2: 'NOT',
    content1_3: ' confer any share rights of the underlying assets.',
    title2: 'What is UST?',
    content2:
      'To start investing, you will need to fund your account with UST, a USD-pegged Terra stablecoin, which means that the value of 1 UST is $1.',
    title3: 'Where do I get UST?',
    content3_1:
      'You can either directly convert your dollars through Moonpay, or buy UST in various crypto-exchanges and send it to your Mirror wallet. To learn more, please refer to the ',
    content3_2: 'Mirror Wallet User Guides',
    content3_3: '.',
    title4: 'What can I invest in?',
    content4:
      'Any assets listed within the application are purchasable at any time of the day, and orders are fulfilled nearly instantaneously.',
    title5: 'How do I cash out?',
    content5:
      'You can withdraw your UST from the Mirror Wallet at any time from your wallet page to send to your exchange accounts.',
    createAccount: 'Create Account',
  },
  promotionView: {
    topTitle: 'Mirror Wallet\nLaunch\nPromotion',
    topContent:
      'To mark the launch of the Mirror Wallet, the top 100 accounts with the highest trading volume of mAssets (calculated in UST) through the Mirror mobile app will win a share of 100,000 UST rewards.',
    seeMore: 'See more',
    tradingVolume: 'My Trading Volume',
    tradingDenom: 'UST',
    tradingDesc:
      '1. The top 10 accounts with the highest trading volume on the Mirror mobile app will win a share of 50,000 UST rewards in proportion to their trading amount.\n\n2. The top 11-100 accounts with the highest trading volume on the Mirror mobile app will win a share of 50,000 UST rewards in proportion to their trading amount.',
    promotionPeriod: 'Promotion Period',
    promotionPeriodValue: 'Dec 17 - Dec 31',
    airdropDate: 'Airdrop Date',
    airdropDateValue: 'Jan 7 00:00',
    airdropDateValueTz: 'UTC',
    minTradingVolume: 'Min Trading Volume',
    minTradingVolumeValue: '50',
    minTradingVolumeValueDenom: 'UST',
    maxReceivableReward: '',
    maxReceivableRewardValue: '',
    maxReceivableRewardValueDenom: '',
    howtoTitle: 'How To\nGet Started',
    step1: 'Step 1',
    step1Content:
      'Deposit UST into the Mirror Wallet through Moonpay top-up or from another UST-supported wallet.',
    step2: 'Step 2',
    step2Content:
      'Trade Mirror Assets within the Mirror Wallet. When you start trading, you will see the the counter above track your total trading volume.',
    step3: 'Step 3',
    step3Content:
      'Users will be airdropped prizes prorated by their total trading volume.',
  },
  recoveryWalletView: {
    title: 'Restore Wallet',
    subTitle:
      'Restore an existing Terra wallet with the associated 24 word seed phrase that you have written down.',
    paste: 'PASTE',
    inputPlaceHolder: 'Enter your seed phrase here',
    confirm: 'Confirm',
  },
}

export const ko = {
  initialView: {
    login1: 'Continue with Apple',
    login2: 'Continue with Google',
    login3: 'Continue with Facebook',
    seed: 'Login with existing Terra wallet',
  },
  agreeView: {
    button: 'Trade at your own risk',
  },
  pinSecurityView: {
    notMatch: 'Passwords do not match. Please try again',
    changed: 'Password has been successfully changed',
    lockedTitle: 'Authentication disabled',
    lockedMessage: 'Please try again in 1 minute',
    authTitle: 'Type in password',
    newTitle: 'Set your password',
    newSubTitle: 'Enter a new 6-digit password to\nunlock your Mirror Wallet',
    newReTitle: 'Confirm your password',
    newReSubTitle:
      'You will only be able to reset your password\nwith your connected account',

    forgotMessage:
      'Please log out of the Mirror Wallet application and re-sign in using your connected Apple/Google/Facebook account to reset your 6-digit password.',
    forgotButton1: 'Cancel',
    forgotButton2: 'Logout',
    forgotPassword: 'Forgot Password',
  },
  bioAuthView: {
    useTouchId: 'Use Touch ID',
    useTouchIdSub: 'Use Touch ID for faster and\neasier access to your account',
    useFaceId: 'Use Face ID',
    useFaceIdSub: 'Use Face ID for faster and\neasier access to your account',
    biometricFailMsg:
      'Biometric authentication failed. Did you rejected permission request?',
    authReason: 'Enable Touch ID for Mirror',
    authTitle: 'Confirm your fingerprint',
    bioErrorTitle: 'Biometric error',
    bioErrorMsg: 'Biometric authentication failed.',
    later: 'Later',
    enable: 'ENABLE',
  },
  mainView: {
    portfolio: 'Portfolio',
    invest: 'Invest',
    searchPlaceholder: 'Discover a Mirror Asset',
  },
  mainTab1View: {
    buyingPower: 'Buying Power',
    balance: 'Balance',
    invested: 'Invested',
    uninvested: 'Un-Invested',
    investedbalance: 'Invested Balance',

    polishYourPortfolio: 'Invest with\nMirror',
    depositToMirror: 'Deposit to\nMirror',
    startInvestingNowWith: 'Start investing now with',
    availableToInvest: 'available to invest',
    deposit: 'Deposit Now',
    symbol: 'UST',
  },
  mainTab2View: {
    mirrorAsset: 'Mirror Asset',
    sortby: 'Sort by',
    done: 'Done',
    ticker: 'Ticker',
    price: 'Price',
    change: '% Change',
  },
  investedDetailView: {
    investedDetail: 'Invested Detail',
    currentValue: 'Current Value',
    amount: 'Amount',
    avgCost: 'Avg Cost',
    ret: 'Return',
    pl: 'UnRealized P/L',
    about: 'About',
    showmore: 'Show More',
    showless: 'Show Less',
    news: 'News',
    buy: 'Buy',
    sell: 'Sell',
  },
  tradeStep1View: {
    availableTo: 'available to',
    buy: 'buy',
    availableToSell: 'available to sell',
    next: 'Next',
  },
  tradeStep2View: {
    amount: 'AMOUNT',
    fees: 'FEES',
    buyingPrice: 'BUYING PRICE',
    inclSpread: 'incl. Spread',
    sellingPrice: 'SELLING PRICE',
    editBuyOrder: 'Reset buy order',
    editSellOrder: 'Reset sell order',
    spread: 'Spread',

    notice: 'NOTICE',
    noticedesc:
      'Mirror Assets do not afford any rights of the underlying asset to Mirror Asset holders. Tracking error may also arise between the underlying asset and its Mirror counterpart.',
    confirm: 'Confirm',

    exceed: 'Fees exceed total trade value.',
  },
  searchView: {
    discover: 'Discover a Mirror Asset',
    cancel: 'Cancel',
  },
  processingView: {
    buySuccess: 'Buy order success',
    sellSuccess: 'Sell order success',
    withdrawSuccess: 'Withdraw success',
    swapSuccess: 'Swap success',
    done: 'Done',
  },
  addressPopupView: {
    address: 'Address',
    qrcode: 'QR code',
    done: 'Done',
    copy: 'Copy',
    copied: 'Copied',
  },
  walletSummaryView: {
    wallet: 'Wallet',
    depositUST: 'Deposit UST',
    funds: 'Funds',
    fundYourWallet: 'Fund Your Wallet',
    deposit: 'Deposit',
    withdrawal: 'Withdrawal',
    depositNow: 'Deposit Now',
    buyNow: 'Buy Now',
    masset: 'mASSET',
    addMasset: '+ mASSET',
    showDecimals: 'Show Decimals',
    depositUpper: 'DEPOSIT',
    withdrawUpper: 'WITHDRAW',
  },
  walletDetailView: {
    notice: 'NOTICE',
    noticedesc:
      'Terra stablecoins other than UST (USD-pegged) must be swapped into UST before Mirror Assets can be purchased.',
    withdraw: 'Withdraw',
    deposit: 'Deposit',
    depositUpper: 'DEPOSIT',
    withdrawUpper: 'WITHDRAW',
  },
  swapView: {
    availableToSwap: 'available to swap',
    swapTo: 'Swap to',
    fees: 'Fees',
  },
  walletTopupView: {
    deposit: 'Deposit',
    pending: 'Pending',
  },
  withdrawView: {
    withdraw: 'Withdraw',
    availableToWithdraw: 'available to withdraw',
    quantity: 'QUANTITY',
    amount: 'AMOUNT',
    address: 'ADDRESS',
    memo: 'MEMO',
    next: 'Next',
  },
  withdrawDetailView: {
    amount: 'AMOUNT',
    fees: 'FEES',
    quantity: 'QUANTITY',
    address: 'ADDRESS',
    memo: 'MEMO',
    withdraw: 'Withdraw',
    insufficientFunds: 'Insufficient Funds',
    notice: 'NOTICE',
    noticedesc:
      'When withdrawing your funds or assets, associated transaction fees are algorithmically decided and charged by the Terra Protocol.',
  },
  privacyView: {
    privacyAndTerms: 'Privacy and terms',
  },
  versionView: {
    version: 'Version',
    current: 'Current',
    newest: 'Newest',
    update: 'Update',
  },
  walletInfoView: {
    walletAddress: 'Wallet address',
    appleAccount: 'Apple ID',
    facebookAccount: 'Facebook Account',
    googleAccount: 'Google Account',
    linkedAccount: 'Linked Account',
    copy: 'Copy',
    copied: 'Copied',
    logout: 'Log out',
  },
  settingView: {
    setting: 'Setting',
    account: 'Account',
    useTouchId: 'Use Touch ID',
    useFaceId: 'Use Face ID',
    biometricAuthHintIOS:
      'It seems Face ID permission is denied or biometric authentication is not enrolled.',
    biometricAuthHintAndroid: 'Biometric authentication is not enrolled.',
    changePassword: 'Change Password',
    privacyAndTerms: 'Privacy and Terms',
    version: 'Version',
    contactUs: 'Contact Us',
    language: 'language',
    selectChain: 'Select Chain',
    selectTorusNet: 'Select TorusNet',
    resetApp: 'Apply and reset',
  },
  walletActivityView: {
    activity: 'Activity',
    all: 'All',
    buy: 'Buy',
    sell: 'Sell',
    deposit: 'Deposit',
    swap: 'Swap',
    withdraw: 'Withdraw',
    empty: 'No past transaction activity',
    itemView: {
      buy: 'Buy',
      sell: 'Sell',
      swap: 'Swap',
      swapTo: 'Swap to',
      deposit: 'Deposit',
      withdraw: 'Withdraw',
      registration: 'REGISTRATION',
    },
  },
  walletActivityFilterView: {
    sortBy: 'Sort by',
    done: 'Done',
    all: 'All',
    buy: 'Buy',
    sell: 'Sell',
    deposit: 'Deposit',
    swap: 'Swap',
    withdraw: 'Withdraw',
    confirm: 'Confirm',
  },
  walletActivityDetailView: {
    orderAmount: 'Order amount',
    senderAddress: 'Sender Address',
    withdrawAddress: 'Withdraw Address',
    amount: 'Amount',
    from: 'From',
    to: 'To',
    quantity: 'Quantity',
    excutionPrice: 'Execution Price',
    fees: 'Fees',
    memo: 'Memo',
    txHash: 'TX Hash',
    buy: 'Buy',
    sell: 'Sell',
    deposit: 'Deposit',
    swap: 'Swap',
    swapTo: 'Swap to',
    withdraw: 'Withdraw',
    registration: 'REGISTRATION',
  },
  spreadPopupView: {
    title: 'Spread',
    content:
      'Estimated fees charged are algorithmically decided and charged by the Mirror Protocol for making the above transaction.',
    more: 'Learn More',
    close: 'Done',
  },
  moonpayPopupView: {
    completedTitle: 'MoonPay Deposit Completed',
    failedTitle: 'MoonPay Deposit Failed',
    completedMessageWithdraw: ' has been successfully withdrawn as ',
    completedMessage1:
      ' has been successfully deposited into your Mirror Wallet.',
    failedMessage1: 'Your MoonPay transaction for ',
    failedMessage2:
      ' has failed. For more detailed information, please check your transaction details on the MoonPay webpage.',
    details: 'Details',
    symbol: 'UST',
    done: 'Done',
  },
  onboardingView: {
    title1: 'What are Mirror Assets?',
    content1_1:
      'Mirror Assets utilize blockchain technology to track the price of underlying assets in real markets but do ',
    content1_2: 'NOT',
    content1_3: ' confer any share rights of the underlying assets.',
    title2: 'What is UST?',
    content2:
      'To start investing, you will need to fund your account with UST, a USD-pegged Terra stablecoin, which means that the value of 1 UST is $1.',
    title3: 'Where do I get UST?',
    content3_1:
      'You can either directly convert your dollars through Moonpay, or buy UST in various crypto-exchanges and send it to your Mirror wallet. To learn more, please refer to the ',
    content3_2: 'Mirror Wallet User Guides',
    content3_3: '.',
    title4: 'What can I invest in?',
    content4:
      'Any assets listed within the application are purchasable at any time of the day, and orders are fulfilled nearly instantaneously.',
    title5: 'How do I cash out?',
    content5:
      'You can withdraw your UST from the Mirror Wallet at any time from your wallet page to send to your exchange accounts.',
    createAccount: 'Create Account',
  },
  promotionView: {
    topTitle: 'Mirror Wallet\nLaunch\nPromotion',
    topContent:
      'To mark the launch of the Mirror Wallet, the top 100 accounts with the highest trading volume of mAssets (calculated in UST) through the Mirror mobile app will win a share of 100,000 UST rewards.',
    seeMore: 'See more',
    tradingVolume: 'My Trading Volume',
    tradingDenom: 'UST',
    tradingDesc:
      '1. The top 10 accounts with the highest trading volume on the Mirror mobile app will win a share of 50,000 UST rewards in proportion to their trading amount.\n\n2. The top 11-100 accounts with the highest trading volume on the Mirror mobile app will win a share of 50,000 UST rewards in proportion to their trading amount.',
    promotionPeriod: 'Promotion Period',
    promotionPeriodValue: 'Dec 17 - Dec 31',
    airdropDate: 'Airdrop Date',
    airdropDateValue: 'Jan 7 00:00',
    airdropDateValueTz: 'UTC',
    minTradingVolume: 'Min Trading Volume',
    minTradingVolumeValue: '50',
    minTradingVolumeValueDenom: 'UST',
    maxReceivableReward: '',
    maxReceivableRewardValue: '',
    maxReceivableRewardValueDenom: '',
    howtoTitle: 'How To\nGet Started',
    step1: 'Step 1',
    step1Content:
      'Deposit UST into the Mirror Wallet through Moonpay top-up or from another UST-supported wallet.',
    step2: 'Step 2',
    step2Content:
      'Trade Mirror Assets within the Mirror Wallet. When you start trading, you will see the the counter above track your total trading volume.',
    step3: 'Step 3',
    step3Content:
      'Users will be airdropped prizes prorated by their total trading volume.',
  },
  recoveryWalletView: {
    title: 'Restore Wallet',
    subTitle:
      'Restore an existing Terra wallet with the associated 24 word seed phrase that you have written down.',
    paste: 'PASTE',
    inputPlaceHolder: 'Enter your seed phrase here',
    confirm: 'Confirm',
  },
}
